name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo.
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set yarn version
        run: corepack enable && yarn set version stable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      # Speed up yarn install dramatically by persisting the yarn cache.
      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          # Ideally we'd have the cache from an identical yarn.lock ready.
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          # Otherwise we'll try and find something decent to start with.
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      # This is useful for debugging; you can install upterm on your machine
      # and connect to the Github server currently running this action.
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
